### ISSUE TITLE
Ability to start/stop service by name

### ISSUE THREAD

**Issue by hopix** [dasMulli/dotnet-win32-service#22]
I can help with implementation if you like?

**Comment by dasMulli** [comment]
I did not implement this because this is possible via the [`ServiceController.Start()`](https://msdn.microsoft.com/de-de/library/yb9w7ytd(v=vs.110).aspx) method which is [available on .netstandard / .net core](https://apisof.net/catalog/System.ServiceProcess.ServiceController.Start()) through [this nuget package](https://www.nuget.org/packages/System.ServiceProcess.ServiceController/).
But I'm open to suggestions. I suppose it would be a cleaner method call (the MSDN sample doesn't work if I read that correctly because the `ServiceName` property is readonly so you'd have to call the static `GetServices()` method and find the one you're looking for).

**Comment by dasMulli** [comment]
Since this is pretty straightforward to do, I'll include it in the next release (hopefully this year).
It will probably look like:

```c#
class Win32ServiceManager {
    Task StartService(string serviceName, params string[] arguments);
    Task StopService(string serviceName);
}
```

Thoughts?

**Comment by hopix** [comment]
Thanks for pointing me to System.ServiceProcess.ServiceController nuget package, I didn't know that it is available from "netstandard1.6" already . Only issue was that I had to update to .net 461 otherwise it wouldn't install.
I see your point - probably no need to duplicate functionality. Like me, people might looking for service start/stop in your lib when they are using it, so maybe it is still worth?
BTW MSDN example is probably just out of date. You need to pass service name in constructor. I tried it and it works.

**Comment by dasMulli** [comment]
Not doing this for now since there isn't really an added value over `System.ServiceProcess.ServiceController` (other than maybe doing it async)
